{"timestamp": "2025-03-05T14:36:34.221333", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_169.py", "startLine": 6, "startColumn": 0, "endLine": 6, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_169.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 6", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 6"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:35.443483", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_174.py", "startLine": 6, "startColumn": 0, "endLine": 6, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_174.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 6", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 6"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:37.021519", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_175.py", "startLine": 10, "startColumn": 0, "endLine": 10, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_175.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 10", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 10"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:38.258780", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_207.py", "startLine": 7, "startColumn": 0, "endLine": 7, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_207.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 7", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 7"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:39.395195", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_76.py", "startLine": 7, "startColumn": 0, "endLine": 7, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_76.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 7", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 7"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:40.610825", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_254.py", "startLine": 8, "startColumn": 0, "endLine": 8, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_254.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 8", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 8"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:41.794719", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_77.py", "startLine": 7, "startColumn": 0, "endLine": 7, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_77.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 7", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 7"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:43.048712", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_22.py", "startLine": 6, "startColumn": 0, "endLine": 6, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_22.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 6", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 6"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:44.424903", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_144.py", "startLine": 8, "startColumn": 31, "endLine": 8, "endColumn": 31}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_144.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 8", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 8"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:45.541607", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_119.py", "startLine": 7, "startColumn": 0, "endLine": 7, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_119.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 7", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 7"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:46.726252", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_258.py", "startLine": 6, "startColumn": 0, "endLine": 6, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_258.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 6", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 6"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:48.031916", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_271.py", "startLine": 7, "startColumn": 0, "endLine": 7, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_271.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 7", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 7"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:49.312692", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_238.py", "startLine": 8, "startColumn": 0, "endLine": 8, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_238.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 8", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 8"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:50.072012", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_201.py", "startLine": 1, "startColumn": 1, "endLine": 1, "endColumn": 1}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_201.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 1", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 1"], "args": ["Syntax Error"]}}
