{"timestamp": "2025-03-05T14:36:34.442167", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_36.py", "startLine": 7, "startColumn": 0, "endLine": 7, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_36.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 7", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 7"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:35.678913", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_232.py", "startLine": 8, "startColumn": 0, "endLine": 8, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_232.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 8", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 8"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:37.311971", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_209.py", "startLine": 7, "startColumn": 0, "endLine": 7, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_209.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 7", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 7"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:38.636755", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_272.py", "startLine": 7, "startColumn": 0, "endLine": 7, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_272.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 7", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 7"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:39.873519", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_196.py", "startLine": 8, "startColumn": 0, "endLine": 8, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_196.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 8", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 8"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:41.094527", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_98.py", "startLine": 7, "startColumn": 0, "endLine": 7, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_98.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 7", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 7"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:42.318215", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_151.py", "startLine": 8, "startColumn": 0, "endLine": 8, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_151.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 8", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 8"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:43.635868", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_34.py", "startLine": 7, "startColumn": 0, "endLine": 7, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_34.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 7", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 7"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:44.934583", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_141.py", "startLine": 7, "startColumn": 0, "endLine": 7, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_141.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 7", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 7"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:46.157317", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_331.py", "startLine": 7, "startColumn": 0, "endLine": 7, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_331.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 7", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 7"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:47.272130", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_226.py", "startLine": 7, "startColumn": 0, "endLine": 7, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_226.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 7", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 7"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:48.510749", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_87.py", "startLine": 8, "startColumn": 0, "endLine": 8, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_87.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 8", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 8"], "args": ["Syntax Error"]}}
{"timestamp": "2025-03-05T14:36:49.607456", "source": {"id": "py/diagnostics/syntax-error", "name": "Could not process some files due to syntax errors", "extractorName": "python"}, "severity": "warning", "location": {"file": "/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_195.py", "startLine": 6, "startColumn": 0, "endLine": 6, "endColumn": 0}, "markdownMessage": "A parse error occurred while processing `/Users/lucywingard/code/codeql_testing/code_samples_for_codeql/python/sample_195.py`, and as a result this file could not be analyzed. Check the syntax of the file using the `python -m py_compile` command and correct any invalid syntax.", "visibility": {"statusPage": true, "cliSummaryTable": true, "telemetry": true}, "attributes": {"traceback": ["\"semmle/python/modules.py\", line 129, in py_ast", "\"semmle/python/modules.py\", line 114, in old_py_ast", "\"semmle/python/parser/__init__.py\", line 153, in parse", "\"semmleFile \"<string>\", line 6", "\"semmle/python/extractor.py\", line 101, in process_source_module", "\"semmle/python/modules.py\", line 101, in ast", "\"semmle/python/modules.py\", line 154, in py_ast", "\"semmle/python/modules.py\", line 148, in py_ast", "\"semmle/python/parser/tsg_parser.py\", line 343, in parse", "\"semmleFile \"<string>\", line 6"], "args": ["Syntax Error"]}}
